[package]
name = "heap"
description = "A powerful stack projects manager"
version = "0.1.0"
readme = "../README.md"
license-file = "../LICENSE.md"
authors = ["HDB-PROGRAMMING <hdbprogramming@gmail.com>"]
edition = "2018"

[dependencies]